//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema.Gestao.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funcionario
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public int Cargo { get; set; }
        public decimal Salario { get; set; }
        public int EmpresaId { get; set; }
    
        public virtual Empresa Empresa { get; set; }
    }
}
